kbb_roadmap/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
urlpatterns = [
    path('', include('landing.urls')),
    path('history/', include('history.urls', namespace='history')),
    path('affiliate/', include('affiliate.urls', namespace='affiliate')),
    path('org/', include('org.urls', namespace='org')),
    path('roadmap/', include('roadmap.urls', namespace='roadmap')),
    path('event/', include('event.urls', namespace='event')),
    path('report/', include('report.urls', namespace='report')),
    path('notification/', include('notification.urls', namespace='notification')),

    path('admin/', admin.site.urls),

    path('user/', include('user.urls', namespace='user')),
    path('donation/', include('donation.urls', namespace='donation')),
    path('comments/', include('comments.urls', namespace='comments')),
    path('user/', include("allauth.urls")),
    
    
    # path('report/', include('report.urls')),

] 
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

org/urls.py
from django.urls import path
from django.urls import include


from . import views
app_name="org"
urlpatterns = [
    
    path('', views.main, name="main"),
    
]

user/urls.py
from django.urls import path

from . import views
app_name='user'


urlpatterns = [
    path('', views.main, name="main"),
    path('logout/', views.logout, name='logout'), 
    path('byname/', views.get_user_by_name, name='get_user_by_name'),
]

user/models.py
from django.contrib.auth.models import AbstractBaseUser
from django.db import models
from django.urls import reverse
# Create your models here.
class User(AbstractBaseUser):
    name = models.CharField(blank=False, max_length=255)
    user_name = models.CharField(blank=False, max_length=255)
    profile_photo = models.ImageField(blank=False)


    def get_absolute_url(self):
        return reverse("users:detail", kwargs={"username":self.user_name})

user/views.py
from django.contrib.auth import get_user_model
from django.shortcuts import render, redirect
from django.contrib import auth
from django.http import QueryDict,JsonResponse


def main(request):
    context = {}
    print(request.user)
    if request.user.is_authenticated:
        from allauth.socialaccount.models import SocialAccount

        
        users = list(SocialAccount.objects.filter(user_id=request.user.id))
        
        if len(users) > 0:
        
            picture = users[0].extra_data.get("picture")
            
            context = {
                "picture":picture
            }
    
    return render(request, 'user/main.html', context)
    



# def login(request):
#     return render(request, 'user/login.html')

def logout(request):
    auth.logout(request)
    return redirect('/')


def get_user_by_name(request):
    queries = QueryDict(request.META.get("QUERY_STRING", None))
    user_name = queries.get("name", None)
    
    users = get_user_model().objects.filter(username__contains=user_name, is_superuser=False)
    users_list = list(users)
    
    """
    Cannot resolve keyword 'name' into field. 
    Choices are: 
    comment_likes, date_joined, email, emailaddress, first_name, groups, id, is_active, is_staff, 
    is_superuser, last_login, last_name, logentry, notificationstatus, password, roadmap_assignee, 
    roadmap_comment_author, roadmap_requester, roadmapagreement, roadmapcomplete, socialaccount, 
    user, user_permissions, username
    """
    # 
    # return HttpResponse(json.dumps({"user_name":user_name}))
    return JsonResponse({"users":[{"id":u.id, "name":u.username} for u in users_list]})





# def google_login(request):
#     scope = GOOGLE_SCOPE_USERINFO + GOOGLE_SCOPE_DRIVE
#     client_id = CLIENT_ID
#     return redirect(f"{GOOGLE_REDIRECT}?client_id={client_id}&response_type=code&redirect_uri={GOOGLE_CALLBACK_URI}&scope={scope}")

templates/user/login.html
{% load socialaccount %}
<h1>Login page</h1>
{% if user.is_authenticated %}
<p>authenticated</p>
<a href="/user/logout">로그아웃</a>
{% else %}
<a href="{% provider_login_url 'google' %}"> 구글 로그인</a>


{% endif %}

templates/user/main.html
{% extends 'base.html' %}
{% load allauth %}
{% load socialaccount %}


{% block style %}
<style>
    .user_section{
        height:60vh;
        padding:1rem;
        display: flex;
        flex-direction: column;
        justify-content: center;
        align-items: center;
        gap:1rem;
    }

    .user_section img{
        border-radius: 50%;
    }
    .user_section a {
        font-size: 1.25rem;
        text-decoration: none;
    }

    .user_section a.google_login{
        display:flex;
        justify-content: center;
        align-items: center;
        gap:1rem;
        padding: 0.5rem 2rem;
        border-radius: 64px;
        background-color: rgba(128,128,128,0.2);
    }
    .user_section a.google_login img{
        width:60px;
    }
</style>
{% endblock %}
{% block title %}
(주) 곡반 보더스 / KBB - 계정
{% endblock %}


{% block content %}

<section class="user_section"> 
    {% if user.is_authenticated %}        
        <p>사용자 정보</p>

        <img src="{{picture}}" />
        <small>아이디: {{user.username}}</small>
        <small>이름: {{user.get_full_name}}</small>
        <small>이메일: {{user.email}}</small>
        <small>최근 접속시간: {{user.last_login}}</small>
            
        <a href="{% url 'user:logout' %}"> 로그아웃 </a>
    {% else %}
        <a class="google_login" href="{% provider_login_url 'google' %}">  
            <img src="/media/internal/web_neutral_rd_na@4x.png" /> 구글 계정으로 계속 하기 
        </a>
    {% endif %}

</section>

{% endblock%}